name: Greet Action
description: greet people
inputs:
  my-secret:
    description: 'tell me a secret'

runs: 
  using: 'composite'
  steps:
    - run: |
        echo "hello config var: vars is not accessible!"
        echo "Hello Input parent inputs are not accessible!"
        echo "Hello Secret: secrets not accessible!"
        echo "conclusion: [composite] actions can only access inputs, and nothing of the parent workflow's context directly" 
        echo "top sekreet" 
      env:
        MY_SECRET: ${{inputs.my-secret}}
      shell: bash