name: Greet Action
description: greet people
inputs:
  my-secret:
    description: 'tell me a secret'

runs: 
  using: 'composite'
  env:
    MY_SECRET: ${{inputs.my-secret}}
  steps:
    - run: |
      echo "hello config var: ${{vars.GREET_NAME}}"
      echo "Hello Input ${{inputs.to-greet}}!"
      echo "Hello Secret (probably redacted): $MY_SECRET"