name: Greet Action
description: greet people
inputs:
  my-secret:
    description: 'tell me a secret'

runs: 
  using: 'composite'
  steps:
    - run: |
        echo "hello config var: vars is not accessible!"
        echo "Hello Input parent inputs are not accessible!"
        echo "Hello Secret (probably redacted): $MY_SECRET" 
      env:
        MY_SECRET: ${{secrets.MY_SECRET}}
      shell: bash