name: Greet Action
description: greet people

runs: 
  using: 'composite'
  env:
    MY_SECRET: ${{secrets.MY_SECRET}}
  steps:
    - run: |
      echo "hello config var: ${{vars.GREET_NAME}}"
      echo "Hello Input ${{inputs.to-greet}}!"
      echo "Hello Secret (probably redacted): "