on:
    push:
      branches: [main]
    repository_dispatch:

        
jobs:
    # resuse-hello-job:
    #     uses: ./.github/workflows/say-hello.yml

    echo-default-vars:
        runs-on: ubuntu-latest
        env:
            FOO: a 1 x
            COERCED: ${{ 'false' == false }}
        steps:
            - run: |
                : ${{env.FOO}} # comment
                echo "COERCED: $COERCED"
                echo "Event: ${{toJson(github.event)}}"
                echo "Event Name: ${{github.event_name}}"
                echo "Event Path: ${{github.event_path}}"
                echo "GITHUB_WORKSPACE = '$GITHUB_WORKSPACE'"
                echo "GITHUB_REF = '$GITHUB_REF'"
                echo "GITHUB_HEAD_REF = '$GITHUB_HEAD_REF'"
                echo "GITHUB_BASE_REF = '$GITHUB_BASE_REF'"
                echo "github.ref = '${{github.ref}}'"
                echo "github.head_ref = '${{github.head_ref}}'"
                echo "github.base_ref = '${{github.base_ref}}'"
                TEST="Foobar"
                echo "TEST=$TEST" >> "$GITHUB_ENV"
                echo "TEST=$TEST"
                echo "env.TEST = ${{env.TEST}}"
            - if: env.TEST == 'FoobAR'
              run: |
                echo $TEST
