name: Play With Artifacts

on:
  push:
    branches: [main]

jobs:
  push-unnamed-artifact-1:
    runs-on: ubuntu-latest
    steps:
        - run: |
            mkdir -p foo/bar
            touch foo/bar/test.txt
        - run: ls -R
        - uses: actions/upload-artifact@v4
          with:
            path: .
            overwrite: true

  push-unnamed-artifact-2:
    needs: [push-unnamed-artifact-1]
    runs-on: ubuntu-latest
    steps:
        - run: |
            mkdir -p fuu/baz
            touch fuu/baz/bamboozle.txt
        - run: ls -R
        - uses: actions/upload-artifact@v4
          with:
            path: .
            overwrite: true

  download-all-artifacts:
    needs: [push-unnamed-artifact-1, push-unnamed-artifact-2]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v4
        - run: ls -R

