name: Play With Artifacts

on:
  push:
    branches: [main]

jobs:
  push-unnamed-artifact-1:
    runs-on: ubuntu-latest
    steps:
        - run: |
            mkdir -p foo/bar
            touch foo/bar/test.txt
        - run: ls -R
        - uses: actions/upload-artifact@v4
          with:
            path: .

  download-all-artifacts:
    needs: [push-unnamed-artifact-1]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/download-artifact@v4
        - run: ls -R

