on:
    push:
      branches: [main]

jobs:
    resuse-hello-job:
        uses: ./.github/workflows/templates/say-hello.yml

    echo-default-vars:
        runs-on: ubuntu-latest
        env:
            FOO: a 1 x
        steps:
            - run: |
                : ${{env.FOO}} # comment
                echo "$GITHUB_WORKSPACE"
                echo "GITHUB_WORKSPACE = '$GITHUB_WORKSPACE'"
                echo "GITHUB_REF = '$GITHUB_REF'"
                echo "GITHUB_HEAD_REF = '$GITHUB_HEAD_REF'"
                echo "GITHUB_BASE_REF = '$GITHUB_BASE_REF'"
                echo "github.ref = '${{github.ref}}'"
                echo "github.head_ref = '${{github.head_ref}}'"
                echo "github.base_ref = '${{github.base_ref}}'"
                TEST="Foobar"
                echo "TEST=$TEST" >> "$GITHUB_ENV"
                echo "TEST=$TEST"
            - if: env.TEST == 'FoobAR'
              run: |
                echo $TEST
