on:
    workflow_call:

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello ${{vars.GREET_NAME}}!"
            - run: echo "Hello Input ${{inputs.to-greet}}!"
