name: Say Hello

on:
  workflow_dispatch:
    inputs:
      to-greet:
        description: 'greet this guy or gal'


jobs:
  say_hello_with_workflow: 
    uses: ./.github/workflows/reusable.yml
  
  say_hello_with_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/greet-action
