name: Say Hello

on:
  workflow_dispatch:
    inputs:
      artifact-name:
        description: 'how to name the artifact'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir target
          echo "Hell, Oh World!" > target/test.txt
      - uses: actions/upload-artifact@v4
        with:
          path: target
          name: ${{inputs.artifact-name}}-hello
