on:
    push:
        branches:
            - main
jobs:
    this-should-not-be-allowed:
        environment: prod
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "hello"