name: Test PR Behaviour

on:
    push:
        branches: ['!main']

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: 'Print Event'
              run: |
                echo "event: $GITHUB_EVENT"
