on:
    workflow_dispatch:
    push:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 (Failing Step)
        run: exit 1
        continue-on-error: true

      - name: Step 2 (Always Runs)
        if: always()
        run: echo "This runs regardless of Step 1 status."

      - name: Step 3 (Dependent on Success)
        if: success()
        run: echo "This runs because the job is still considered successful."
