name: Test PR Paths Behaviour
on:
    pull_request:
        branches: [main]
        paths:
            - '**.foo'
jobs:
    dummy:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"