name: Test PR Paths Behaviour
on:
    pull_request:
        branches: [main]
jobs:
    dummy:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Pushed Commit $GITHUB_EVENT_PULL_REQUEST_HEAD_SHA"
                echo "Pushed Commit ${{github.event.pull_request.head.sha}}"