name: Test PR Paths Behaviour
on:
    pull_request:
        branches: [main]
jobs:
    dummy:
        runs-on: ubuntu-latest
        steps:
            - env:
                PUSHED_SHA: ${{github.event.pull_request.head.sha}}
              run: |
                echo "Pushed Commit $PUSHED_SHA"
                git diff-tree --no-commit-id --name-only $PUSHED_SHA -r > commit-diff.txt
                echo commit-diff.txt